version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:1.9
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:1.9
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mongodb:
    image: quay.io/debezium/example-mongodb:1.9
    hostname: mongodb
    ports:
     - 5151:27017
    environment:
     - MONGODB_USER=debezium
     - MONGODB_PASSWORD=dbz
    volumes:
      # mkdir mongo_db_path && chown -R 1000:1000 mongo_db_path
      - /home/ubuntu/mongodb4/db_backup:/data/db
  connect:
    image: quay.io/debezium/connect:1.9
    ports:
     - 8083:8083
    links:
     - kafka
     - mongodb
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     
# export DEBEZIUM_VERSION=1.9
# quay.io/debezium/example-mongodb:${DEBEZIUM_VERSION}
